import { Creator } from "./creator";

export const MOCK_CREATORS: Creator[] = [
  {
    id: 1,
    name: "Sarah Johnson",
    email: "sarah@example.com",
    shardId: "SHARD_001_CREATOR_SJ",
    platforms: {
      instagram: { username: "@sarahjohnson", followers: 250000, verified: true },
      tiktok: { username: "@sarahjohnson", followers: 180000, verified: true },
      youtube: { username: "Sarah Johnson", followers: 500000, verified: false },
    },
    audienceData: {
      engagementRate: 4.2,
      topLocations: ["US", "UK", "CA"],
      ageRanges: { "19-24": 35, "25-34": 40, "13-18": 15, "35-44": 10 },
      totalFollowers: 930000,
      growthRate: 8.5,
    },
    tags: {
      niche: ["Fashion", "Lifestyle"],
      style: ["Minimalist", "Luxury"],
      audience: ["Gen-Z", "Millennials"],
      values: ["Sustainability"],
      narrative: ["Educational", "Entertaining"],
    },
    status: "verified",
    completedCampaigns: 12,
    totalEarnings: 250000,
    lastVerified: "2 weeks ago",
    contentSamples: [
      "https://example.com/sample1",
      "https://example.com/sample2",
      "https://example.com/sample3",
    ],
    campaignHistory: [
      { id: 1, name: "Summer Collection 2024", brand: "Nike", status: "completed" },
      { id: 2, name: "Spring Launch", brand: "Adidas", status: "completed" },
    ],
    flags: [],
    averageCompletionRate: 95,
  },
  {
    id: 2,
    name: "Mike Chen",
    email: "mike@example.com",
    shardId: "SHARD_002_CREATOR_MC",
    platforms: {
      instagram: { username: "@mikechen", followers: 150000, verified: true },
      tiktok: { username: "@mikechen", followers: 1200000, verified: true },
      youtube: { username: "Mike Chen", followers: 0, verified: false },
    },
    audienceData: {
      engagementRate: 6.1,
      topLocations: ["US", "SG", "JP"],
      ageRanges: { "13-18": 45, "19-24": 35, "25-34": 15, "35-44": 5 },
      totalFollowers: 1350000,
      growthRate: 12.3,
    },
    tags: {
      niche: ["Tech", "Gaming"],
      style: ["Casual", "Authentic"],
      audience: ["Gen-Z"],
      values: ["Innovation"],
      narrative: ["Entertaining"],
    },
    status: "active",
    completedCampaigns: 8,
    totalEarnings: 180000,
    lastVerified: "1 month ago",
    contentSamples: [
      "https://example.com/sample1",
      "https://example.com/sample2",
    ],
    campaignHistory: [
      { id: 3, name: "Gaming Gear Launch", brand: "Razer", status: "completed" },
    ],
    flags: [],
    averageCompletionRate: 92,
  },
  {
    id: 3,
    name: "Emma Wilson",
    email: "emma@example.com",
    shardId: "SHARD_003_CREATOR_EW",
    platforms: {
      instagram: { username: "@emmawilson", followers: 320000, verified: true },
      tiktok: { username: "@emmawilson", followers: 450000, verified: true },
      youtube: { username: "Emma Wilson", followers: 250000, verified: true },
    },
    audienceData: {
      engagementRate: 3.8,
      topLocations: ["US", "AU", "NZ"],
      ageRanges: { "25-34": 40, "35-44": 30, "19-24": 20, "13-18": 10 },
      totalFollowers: 1020000,
      growthRate: 5.2,
    },
    tags: {
      niche: ["Beauty", "Wellness"],
      style: ["Professional", "Authentic"],
      audience: ["Millennials", "Gen-X"],
      values: ["Inclusivity", "Sustainability"],
      narrative: ["Educational"],
    },
    status: "flagged",
    completedCampaigns: 15,
    totalEarnings: 420000,
    lastVerified: "3 weeks ago",
    contentSamples: [
      "https://example.com/sample1",
      "https://example.com/sample2",
      "https://example.com/sample3",
      "https://example.com/sample4",
    ],
    campaignHistory: [
      { id: 4, name: "Wellness Series", brand: "Olay", status: "completed" },
      { id: 5, name: "Beauty Launch", brand: "MAC", status: "completed" },
    ],
    flags: [
      {
        id: "flag_1",
        type: "suspicious_engagement",
        description: "Engagement spike detected (+300% in 3 days)",
        severity: "high",
      },
    ],
    averageCompletionRate: 98,
  },
];
