import { Campaign } from "./campaign";

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 1,
    name: "Summer Collection 2024",
    brand: "Nike",
    budget: 500000,
    status: "live",
    statusPipeline: "live",
    members: 4,
    creatorsAssigned: 3,
    creatorsNeeded: 5,
    brief: "Launch our new summer collection with a focus on sustainability and innovation",
    requirements: "5 posts per creator, 1 collaboration video, monthly reporting",
    tasks: [
      { id: 1, title: "Product Photos", status: "completed", assignedTo: 3 },
      { id: 2, title: "Collab Video", status: "in_progress", assignedTo: 1 },
      { id: 3, title: "Content Review", status: "pending", assignedTo: 2 },
    ],
    assignedCreators: [
      { id: 1, name: "Sarah Johnson", status: "active" },
      { id: 2, name: "Mike Chen", status: "active" },
      { id: 3, name: "Emma Wilson", status: "active" },
    ],
    suggestedCreators: [
      { id: 4, name: "Alex Rodriguez", matchScore: 8.7 },
      { id: 5, name: "Jessica Lee", matchScore: 8.2 },
    ],
    budgetTracking: {
      total: 500000,
      allocated: 450000,
      spent: 200000,
      remaining: 300000,
    },
    contentPipeline: [
      { title: "Product Photos", dueDate: "2024-06-15", deliveredCount: 3 },
      { title: "Collab Video", dueDate: "2024-07-01", deliveredCount: 0 },
    ],
    createdAt: "2024-05-01",
    startDate: "2024-06-01",
    endDate: "2024-08-31",
  },
  {
    id: 2,
    name: "Spring Launch",
    brand: "Adidas",
    budget: 350000,
    status: "active",
    statusPipeline: "matching",
    members: 3,
    creatorsAssigned: 2,
    creatorsNeeded: 4,
    brief: "Promote new spring athletic wear collection",
    requirements: "4 posts per creator, product reviews",
    tasks: [
      { id: 4, title: "Review Content", status: "pending", assignedTo: 2 },
    ],
    assignedCreators: [
      { id: 1, name: "Sarah Johnson", status: "active" },
    ],
    suggestedCreators: [
      { id: 2, name: "Mike Chen", matchScore: 8.9 },
      { id: 3, name: "Emma Wilson", matchScore: 7.8 },
      { id: 4, name: "Alex Rodriguez", matchScore: 7.5 },
    ],
    budgetTracking: {
      total: 350000,
      allocated: 280000,
      spent: 120000,
      remaining: 230000,
    },
    contentPipeline: [],
    createdAt: "2024-04-15",
    startDate: "2024-05-01",
    endDate: "2024-07-31",
  },
  {
    id: 3,
    name: "Gaming Gear Launch",
    brand: "Razer",
    budget: 250000,
    status: "draft",
    statusPipeline: "draft",
    members: 1,
    creatorsAssigned: 0,
    creatorsNeeded: 6,
    brief: "Launch new gaming peripherals",
    requirements: "Game reviews, unboxing videos",
    tasks: [],
    assignedCreators: [],
    suggestedCreators: [
      { id: 2, name: "Mike Chen", matchScore: 9.2 },
      { id: 4, name: "Alex Rodriguez", matchScore: 8.6 },
    ],
    budgetTracking: {
      total: 250000,
      allocated: 0,
      spent: 0,
      remaining: 250000,
    },
    contentPipeline: [],
    createdAt: "2024-05-20",
    startDate: null,
    endDate: null,
  },
];
